```{r data generation, echo = FALSE, results = "hide"}
library(cowplot)
library(magick)
library(tidyverse)
library(patchwork)
library(glue)
theme_set(theme_minimal())

symmetries <- c("rotation", "mirror", "centre\\ of\\ symmmetry", "roto-inversion", "screw\\ rotation", "glide\\ plane")

groups <- c("P2/m", "Pmm2", "Pmn2_1", "P222_1", "Pcc2", "Pmc2_1", "Pba2", "P4/n", "Pmma", "P2/c", "Pc")

image_index <- sample(1:11, 1)
image_url <- glue("/home/eugene/Desktop/Academic/Science4/ManuTech/quizes/2020/space_groups/xtal0{image_index}.png")

image_line <- (ggdraw() + draw_image(image_url[1]))

solutions <- case_when(image_index == 1 ~ c(T, T, T, T, F, F),
                       image_index == 2 ~ c(T, T, F, F, F, F),
                       image_index == 3 ~ c(F, T, F, F, T, T),
                       image_index == 4 ~ c(T, F, F, F, T, F),
                       image_index == 5 ~ c(T, F, F, F, F, T),
                       image_index == 6 ~ c(F, T, F, F, T, T),
                       image_index == 7 ~ c(T, F, F, F, F, T),
                       image_index == 8 ~ c(T, F, T, T, F, T),
                       image_index == 9 ~ c(T, T, T, F, F, T),
                       image_index == 10 ~ c(T, F, T, F, F, T),
                       image_index == 11 ~ c(F, F, F, F, F, T))

## QUESTION/ANSWER GENERATION
questions <- symmetries
solutions <- solutions
explanations <- character(6)

explanations[1] <- "2-fold rotation axes are black ellipses,\n4-fold rotation axes are black diamonds"
explanations[2] <- "Mirrors are the thick black lines"
explanations[3] <- "Centres of symmetry are small empty circles"
explanations[4] <- "Roto-inversions are ellipses / diamonds with a white circle in the centre"
explanations[5] <- "2-fold screw rotations are galaxies, 4-fold are diamonds with tails"
explanations[6] <- "Glide planes can be an angle in the bottom left corner with the arrow,\nor dotted/dashed lines,\nor half arrows with 1/2, 1/4 beside them"

# explanations[1] <- "2-fold rotation axes, at corners for example,\nthe white circles are centres of symmetry,\nthe mirror is shown by the two angled lines in the bottom left corner,\nand the roto-inversion is implied"
# explanations[2] <- "2-fold rotation axes, at corners for example,\nthe mirrors are the thick black lines"
# explanations[3] <- "Thick black lines are mirrors,\nthe galaxies are screw rotations,\nthe dashed lines are glide"
# explanations[4] <- "The arrows are rotation axes,\nthe galaxies are screw rotations"
# explanations[5] <- "2-fold rotations, at the corners for example,\ndotted lines are glide planes"
# explanations[6] <- "Solid lines are mirrors,\ngalaxies are screw rotations,\ndotted lines are glide planes"
# explanations[7] <- "2-fold rotations, at the corners for example,\ndashed lines are glide planes"
# explanations[8] <- "Black diamonds are 4-fold rotations,\nwhite circles are centres of symmetry,\nwhite diamonds are roto-inversions,\nangle in the bottom left corner with the arrow is a glide plane"
# explanations[9] <- "Black ellipses are rotations,\nthick black lines are mirrors,\nwhite circles are centres of symmetry,\nangle in the bottom left corner with the arrow is a glide plane"
# explanations[10] <- "Black ellipses are rotations,\nwhite circles are centres of symmetry,\nangle in the bottom left corner with the arrow is a glide plane"
# explanations[11] <- "Angle in the bottom left corner with the arrow is a glide plane"

true_explanations <- explanations[solutions]
```

Question
========
The diagram below is of a space group $`r groups[image_index]`$. Examine the space group diagram and check the boxes beside the symmetry elements present in the group.
  
```{r boxplot, echo = FALSE, results = "hide", fig.height = 4, fig.width = 10, fig.path = "", fig.cap = ""}
image_line
```


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(glue("${questions}$"), markup = "markdown")
```


Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(solutions, "True", "False"), explanations, markup = "markdown")
```

Meta-information
================
extype: mchoice
exsolution: `r mchoice2string(solutions)`
exname: Space Groups